name: Conda build
on:
  push:
    branches:
    - master
  release:
    types:
    - created
  repository_dispatch:
    types:
      - conda-build

jobs:
  build:
    uses: sot/skare3/.github/workflows/package_build.yml@master
    with:
      noarch: false
    secrets:
      CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
      CHANDRA_XRAY_TOKEN: ${{ secrets.CHANDRA_XRAY_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}

  upload:
    needs: [build]
    uses: sot/skare3/.github/workflows/package_upload.yml@master
    with:
      channel: masters
